### PR TITLE
Package improvements

### LINKED ISSUE #3: setq-local requires emacs > 24,3

### PR DESCRIPTION
**Pull request by i4ki**
Some improvements pointed out in melpa review: https://github.com/melpa/melpa/pull/3996
- Use `make-local-variable` instead of `setq-local`. Closes #3 
- Fix namespace (Change from `nashfmt-*` to `nash-fmt-*`).
- Fix instructions about the use of `nash-fmt-before-save`.

@purcell Can you take a look?

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.
- Re. `setq-local`, it's frowned upon to "shim" missing core functions like that. Better in this case to just say `(set (make-local-variable 'comment-start) ...)`, since `setq-local` is only used twice anyway.
- The `nash-fmt-before-save` hook still doesn't really follow what I suggested in melpa/melpa#3996 -- the `enable-on-save` function should be using the `local` flag for `add-hook` when it adds an on-save function. And then you don't need to check the major mode, because you'd tell users to only use the `enable-on-save` function in `nash-mode`

I forgot to mention it previously, but you should also not distribute the `-autoloads` file: `package.el` will generate this upon installation, so there's no need to have it in your repo, and indeed it might lead to problems if it gets outdated.

**Comment by i4ki** [comment]
@purcell What do you think now?

Thanks for you help!

**Comment by purcell** [comment]
Looks good, but you can make things more straightforward if you just change

``` el
;;;###autoload
(defun nash-fmt-before-save ()
  "Add this to .emacs to run nashfmt on the current buffer when saving:
  (add-hook 'nash-mode-hook 'nash-fmt-enable-on-save)
  where nash-fmt-enable-on-save would be a function which calls
 (add-hook 'before-save-hook 'nash-fmt-before-save nil 'local)"
  (interactive)
(nash-fmt))
```

to something like this:

``` el
;;;###autoload
(defun nash-fmt-enable-on-save ()
  "Add this to `nash-mode-hook' to run nashfmt on the current buffer when saving.
e.g. include something like the following in your emacs startup file:
   (add-hook 'nash-mode-hook 'nash-fmt-enable-on-save)"
  (interactive)
  (add-hook 'before-save-hook 'nash-fmt nil 'local))
```

**Comment by purcell** [comment]
(Sorry, small mistake: see edited version of previous comment.)

**Comment by i4ki** [comment]
Thank you!

**Pull request merged**
